### ISSUE TITLE
splitting at tree level vs. forest level

### ISSUE THREAD

**Issue by jovo** [neurodata/progressive-learning#89]
i think our current code splits at tree level rather than forest level, is this true?
is so, can somebody explain the pro's and con's of this decision, i've forgotten.
thanks

**Comment by levinwil** [comment]
@jovo cold you please expand upon what it means to split at tree level rather than forest level? Is this referring to splitting the data into decider/voter/transformer data, or splitting trees into nodes?

**Comment by jovo** [comment]
the former

On Tue, Sep 8, 2020 at 5:15 PM Will LeVine <notifications@github.com> wrote:

>
>
>
>
>
>
>
>
>
>
>
> *      External Email - Use Caution      *
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> @jovo
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjovo&data=02%7C01%7Cjovo%40jhu.edu%7Cba61012c37534fe8023008d8543c4853%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637351965167199722&sdata=k516%2FvGDqfaHYlWamNOS7jjsIJ8NhacOXrSgTIZqbgk%3D&reserved=0>
> cold you please expand upon what it means
>
> to split at tree level rather than forest level? Is this referring to
> splitting the data into decider/voter/transformer data, or splitting trees
> into nodes?
>
>
> —
>
>
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly,
>
> view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fprogressive-learning%2Fissues%2F89%23issuecomment-689140239&data=02%7C01%7Cjovo%40jhu.edu%7Cba61012c37534fe8023008d8543c4853%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637351965167209712&sdata=%2BDE6qHqwP21Wc%2FYl2S959Yu7H6cvxzryx9Nx4Henr54%3D&reserved=0>,
> or
>
> unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4VPY73ZOUWP2LFTINTSE2NGHANCNFSM4RAD2XBA&data=02%7C01%7Cjovo%40jhu.edu%7Cba61012c37534fe8023008d8543c4853%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637351965167209712&sdata=pq8cdaNDZ5yEo2KVErmGctu3vA0NQXpNb%2FeAfn6t6Mg%3D&reserved=0>
> .
>
>
>
>
>
>
>
>
> --
Typed with thumbs

**Comment by levinwil** [comment]
The process of splitting the data within a single task that uses bagging goes as follows:
1. Split off the data into decider data (if decider data is used). If there is decider data, this data is theoretically used to combine the voter outputs for a single task in some meaningful way beyond average pipelined into argmax. This data is the same across trees - the reason being it is used (in theory) to evaluate how well each tree does to decide a downstream weighting scheme, and I thought it made sense to use the same dataset to perform those evaluations to compare apples to apples.
2. Within each component transformer/voter pair in the bag, split the data into transformer data and voter data to train each transformer and then fill in posteriors. This transformer/voter data-splitting process is performed within each tree and independent of the transformer/voter data-splitting process of all other trees within the same bag. This data is different across trees, as this is a standard way to decorrelate errors in a bagging classifier.

So, the quick answer to your question is: the decider data is split at a forest level, so that we combine voter outputs in light of apples-to-apples evaluations; the transformer/voter data is split at a tree level, to decorrelate errors across the trees in each forest. 

Does that make sense?

**Comment by jovo** [comment]
yes, thanks

On Tue, Sep 8, 2020 at 6:29 PM Will LeVine <notifications@github.com> wrote:

>
> *      External Email - Use Caution      *
>
>
>
> The process of splitting the data within a single task that uses bagging
> goes as follows:
>
>    1. Split off the data into decider data (if decider data is used). If
>    there is decider data, this data is theoretically used to combine the voter
>    outputs for a single task in some meaningful way beyond average pipelined
>    into argmax. This data is the same across trees - the reason being it is
>    used (in theory) to evaluate how well each tree does to decide a downstream
>    weighting scheme, and I thought it made sense to use the same dataset to
>    perform those evaluations to compare apples to apples.
>    2. Within each component transformer/voter pair in the bag, split the
>    data into transformer data and voter data to train each transformer and
>    then fill in posteriors. This transformer/voter data-splitting process is
>    performed within each tree and independent of the transformer/voter
>    data-splitting process of all other trees within the same bag. This data is
>    different across trees, as this is a standard way to decorrelate errors in
>    a bagging classifier.
>
> So, the quick answer to your question is: the decider data is split at a
> forest level, so that we combine voter outputs in light of apples-to-apples
> evaluations; the transformer/voter data is split at a tree level, to
> decorrelate errors across the trees in each forest.
>
> Does that make sense?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fprogressive-learning%2Fissues%2F89%23issuecomment-689169510&data=02%7C01%7Cjovo%40jhu.edu%7C97038b64e21b4e64fbf808d85446a673%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637352009699996007&sdata=4FKvAajw3JjZ4%2F2Oe82OtrgSr3e1oGmUqEVjdI2MGqI%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4RFZRS2H4F5JGFPMWTSE2V4NANCNFSM4RAD2XBA&data=02%7C01%7Cjovo%40jhu.edu%7C97038b64e21b4e64fbf808d85446a673%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637352009699996007&sdata=slzzpDxWEVInm1L3fQvFFYmtjC%2FTcf5aDElDUMtMS9k%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
Think I can do better? Tell me how <https://forms.gle/iEad8byD89eTPdYx6>!
